#!/bin/bash

brctl addbr br0
ip netns add gigport

brctl setageing br0 0

ip link add dev veth0 type veth peer name veth0-1

# creates and defines IP for dummy interfaces
ip link add lorasend type dummy
ip link add lorarecv type dummy
ip addr add 192.168.15.1/24 dev lorasend
ip addr add 192.168.15.2/24 dev lorarecv

ip link set dev veth0 address 10:04:00:00:00:00
ip link set dev veth0-1 address 10:04:00:00:00:10
ip link set dev veth0 up
ip link set dev veth0-1 up

ethtool -K veth0 tx off
ethtool -K veth0-1 tx off

brctl addif br0 veth0-1

ip link set dev veth0 up
ip link set dev veth0-1 up

# starts the bmv2 switch
systemctl stop t4p4s-switch
echo 'three-ports' > /root/t4p4s-switch
systemctl start bmv2.service